/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    news: News;
    events: Event;
    parishes: Parish;
    ministries: Ministry;
    priests: Priest;
    'pope-messages': PopeMessage;
    'bishop-messages': BishopMessage;
    publications: Publication;
    magazines: Magazine;
    archives: Archive;
    schools: School;
    clinics: Clinic;
    'children-programs': ChildrenProgram;
    'small-christian-communities': SmallChristianCommunity;
    'geez-calendar-entries': GeezCalendarEntry;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    parishes: ParishesSelect<false> | ParishesSelect<true>;
    ministries: MinistriesSelect<false> | MinistriesSelect<true>;
    priests: PriestsSelect<false> | PriestsSelect<true>;
    'pope-messages': PopeMessagesSelect<false> | PopeMessagesSelect<true>;
    'bishop-messages': BishopMessagesSelect<false> | BishopMessagesSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    magazines: MagazinesSelect<false> | MagazinesSelect<true>;
    archives: ArchivesSelect<false> | ArchivesSelect<true>;
    schools: SchoolsSelect<false> | SchoolsSelect<true>;
    clinics: ClinicsSelect<false> | ClinicsSelect<true>;
    'children-programs': ChildrenProgramsSelect<false> | ChildrenProgramsSelect<true>;
    'small-christian-communities': SmallChristianCommunitiesSelect<false> | SmallChristianCommunitiesSelect<true>;
    'geez-calendar-entries': GeezCalendarEntriesSelect<false> | GeezCalendarEntriesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ti') | ('en' | 'ti')[];
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    homepage: Homepage;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: 'en' | 'ti';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * CMS users and their editorial roles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  /**
   * Determines which content areas this user can edit.
   */
  role: 'super-admin' | 'chancery-editor' | 'parish-editor' | 'youth-editor' | 'catechist-editor' | 'media-editor';
  /**
   * Required for parish-editor role — limits edit scope to this parish.
   */
  assignedParish?: (number | null) | Parish;
  profilePhoto?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * All parishes within the Eparchy of Segeneyti.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parishes".
 */
export interface Parish {
  id: number;
  name: string;
  slug: string;
  vicariate?: ('segeneyti' | 'adi-keyih' | 'dekemhare' | 'adi-ugri' | 'diaspora') | null;
  region?: string | null;
  featuredImage?: (number | null) | Media;
  /**
   * Name of the patron saint of this parish.
   */
  patron?: string | null;
  /**
   * Parish feast day in Ge'ez calendar notation (e.g. '29 Nehase').
   */
  feastDate?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  history?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  pastor?: (number | null) | Priest;
  contact?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    /**
     * Link to Google Maps or similar.
     */
    mapUrl?: string | null;
  };
  massTimes?:
    | {
        day?: ('Sunday' | 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday') | null;
        time?: string | null;
        language?: ('Tigrinya' | 'English' | 'Arabic' | 'Other') | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Images, documents, and other media assets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive alt text for accessibility and SEO.
   */
  alt?: string | null;
  caption?: string | null;
  /**
   * Photo credit or source attribution.
   */
  credit?: string | null;
  category?: ('general' | 'event' | 'parish' | 'clergy' | 'document') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Priests, deacons, and clergy of the Eparchy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "priests".
 */
export interface Priest {
  id: number;
  fullName: string;
  slug: string;
  title: 'Rev. Fr.' | 'Msgr.' | 'Bishop' | 'Archbishop' | 'Cardinal' | 'Deacon' | 'Brother' | 'Sister';
  status: 'active' | 'retired' | 'deceased' | 'on-leave';
  photo?: (number | null) | Media;
  /**
   * Official role/position (e.g. "Pastor, St. Mary Parish", "Vicar General").
   */
  assignment?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  parish?: (number | Parish)[] | null;
  ordinationDate?: string | null;
  birthDate?: string | null;
  education?:
    | {
        institution: string;
        degree?: string | null;
        year?: number | null;
        id?: string | null;
      }[]
    | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Static informational pages (About, History, Contact, etc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path segment (e.g. "about", "history").
   */
  slug: string;
  status: 'draft' | 'published';
  heroImage?: (number | null) | Media;
  hero?: {
    heading?: string | null;
    subheading?: string | null;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Eparchy news articles and announcements.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Auto-generated from title. Used in the URL.
   */
  slug: string;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  category?: ('eparchy' | 'vatican' | 'pastoral' | 'community' | 'social' | 'announcement') | null;
  featuredImage?: (number | null) | Media;
  /**
   * Short summary shown in news listings and social previews (max 160 chars).
   */
  excerpt?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (number | null) | User;
  relatedNews?: (number | News)[] | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Eparchy-wide and parish-level events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published' | 'cancelled';
  eventType?:
    | ('liturgical' | 'feast' | 'youth' | 'community' | 'education' | 'social' | 'pilgrimage' | 'conference' | 'other')
    | null;
  featuredImage?: (number | null) | Media;
  excerpt?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startDate: string;
  endDate?: string | null;
  isAllDay?: boolean | null;
  location?: {
    name?: string | null;
    address?: string | null;
    googleMapsUrl?: string | null;
  };
  parish?: (number | null) | Parish;
  organizer?: (number | null) | User;
  isRecurring?: boolean | null;
  /**
   * Link to the corresponding Ge'ez liturgical calendar entry.
   */
  geezCalendarRef?: (number | null) | GeezCalendarEntry;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Ge'ez liturgical calendar entries — feasts, fasts, and saints' days.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geez-calendar-entries".
 */
export interface GeezCalendarEntry {
  id: number;
  title: string;
  slug: string;
  isFasting?: boolean | null;
  feastRank?: ('major' | 'minor' | 'memorial' | 'optional-memorial' | 'fasting' | 'ordinary') | null;
  liturgicalColor?: ('white' | 'red' | 'purple' | 'green' | 'black' | 'gold') | null;
  geezDate: {
    month:
      | 'meskerem'
      | 'tikmt'
      | 'hidar'
      | 'tahsas'
      | 'tir'
      | 'yekatit'
      | 'megabit'
      | 'miyazya'
      | 'ginbot'
      | 'sene'
      | 'hamle'
      | 'nehase'
      | 'pagume';
    day: number;
  };
  gregorianEquivalent?: {
    month?: number | null;
    day?: number | null;
  };
  /**
   * Name of the saint or mystery commemorated on this day.
   */
  saint?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  readings?: {
    firstReading?: string | null;
    psalm?: string | null;
    gospel?: string | null;
  };
  /**
   * Specific fasting rules for this day.
   */
  fastingNotes?: string | null;
  relatedEvents?: (number | Event)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Eparchy and parish-level ministry groups.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries".
 */
export interface Ministry {
  id: number;
  name: string;
  slug: string;
  status: 'active' | 'inactive';
  type:
    | 'youth-council'
    | 'catechists'
    | 'children'
    | 'small-christian-community'
    | 'lay-apostolate'
    | 'caritas'
    | 'women-league'
    | 'men-league'
    | 'choir'
    | 'other';
  featuredImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Brief mission statement.
   */
  mission?: string | null;
  /**
   * Leave blank for eparchy-wide ministries.
   */
  parish?: (number | null) | Parish;
  leader?: {
    name?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  meetingInfo?: {
    /**
     * e.g. Every Sunday after 9am Mass
     */
    schedule?: string | null;
    venue?: string | null;
  };
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Papal encyclicals, apostolic exhortations, and messages from the Holy Father.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pope-messages".
 */
export interface PopeMessage {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  documentType?:
    | (
        | 'encyclical'
        | 'apostolic-exhortation'
        | 'apostolic-letter'
        | 'apostolic-constitution'
        | 'message'
        | 'homily'
        | 'audience'
        | 'other'
      )
    | null;
  featuredImage?: (number | null) | Media;
  /**
   * Opening lines or a key excerpt, shown in listings.
   */
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * PDF copy of the full document.
   */
  document?: (number | null) | Media;
  /**
   * Link to the original Vatican document (vatican.va).
   */
  sourceUrl?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Pastoral letters, homilies, and official messages from the Bishop.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bishop-messages".
 */
export interface BishopMessage {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  messageType?:
    | ('pastoral-letter' | 'homily' | 'encyclical-response' | 'christmas' | 'easter' | 'extraordinary' | 'general')
    | null;
  featuredImage?: (number | null) | Media;
  excerpt?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional PDF version of this message.
   */
  document?: (number | null) | Media;
  /**
   * Show on homepage.
   */
  isFeatured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Downloadable documents, booklets, and pastorals.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  slug: string;
  category: 'pastoral' | 'liturgical' | 'educational' | 'youth' | 'social' | 'official' | 'prayer' | 'other';
  language?: ('ti' | 'en' | 'ar' | 'it' | 'multi') | null;
  publishedAt?: string | null;
  coverImage?: (number | null) | Media;
  description?: string | null;
  /**
   * The main document file (PDF recommended).
   */
  file: number | Media;
  /**
   * Human-readable file size (e.g. "2.4 MB").
   */
  fileSize?: string | null;
  /**
   * Number of pages in the document.
   */
  pageCount?: number | null;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Eparchy magazine issues (e.g. Tesfanet, Qal Hiwet).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazines".
 */
export interface Magazine {
  id: number;
  title: string;
  slug: string;
  publishedAt: string;
  coverImage?: (number | null) | Media;
  /**
   * Issue number within the year.
   */
  issueNumber?: number | null;
  year: number;
  /**
   * Volume number.
   */
  volume?: number | null;
  /**
   * Summary of this issue's contents.
   */
  description?: string | null;
  /**
   * Full PDF of the magazine issue.
   */
  document: number | Media;
  featuredArticles?:
    | {
        articleTitle: string;
        pageNumber?: number | null;
        author?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Show as "Latest Issue" on the publications page.
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Historical and official documents for the Eparchy archive.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archives".
 */
export interface Archive {
  id: number;
  title: string;
  slug: string;
  year: number;
  category: 'official' | 'pastoral' | 'historical' | 'correspondence' | 'council' | 'reports' | 'other';
  accessLevel: 'public' | 'restricted';
  description?: string | null;
  files: {
    file: number | Media;
    /**
     * Document title or description.
     */
    label?: string | null;
    language?: ('ti' | 'en' | 'ar' | 'it' | 'other') | null;
    id?: string | null;
  }[];
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catholic schools operated by or affiliated with the Eparchy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools".
 */
export interface School {
  id: number;
  name: string;
  slug: string;
  status: 'active' | 'inactive';
  level: 'kindergarten' | 'primary' | 'middle' | 'secondary' | 'vocational' | 'higher' | 'combined';
  featuredImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  parish?: (number | null) | Parish;
  contact?: {
    address?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  principalName?: string | null;
  foundedYear?: number | null;
  /**
   * Approximate current enrollment.
   */
  studentCount?: number | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Medical facilities affiliated with the Eparchy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinics".
 */
export interface Clinic {
  id: number;
  name: string;
  slug: string;
  status: 'active' | 'inactive';
  facilityType: 'hospital' | 'health-centre' | 'clinic' | 'dispensary' | 'pharmacy' | 'mother-child';
  featuredImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  parish?: (number | null) | Parish;
  contact?: {
    address?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  services?:
    | {
        serviceName: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  openingHours?: string | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catechism, Sunday school, and other children ministry programs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "children-programs".
 */
export interface ChildrenProgram {
  id: number;
  name: string;
  slug: string;
  status: 'active' | 'inactive' | 'seasonal';
  /**
   * Target age group (e.g. "6–12 years").
   */
  ageGroup?: string | null;
  featuredImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Overview of the program curriculum or topics covered.
   */
  curriculum?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  parish?: (number | null) | Parish;
  coordinator?: {
    name?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  /**
   * Meeting times and frequency.
   */
  schedule?: string | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Small Christian Communities (SCCs) within each parish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "small-christian-communities".
 */
export interface SmallChristianCommunity {
  id: number;
  name: string;
  slug: string;
  status: 'active' | 'inactive';
  parish: number | Parish;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Geographic area or neighborhood this SCC covers.
   */
  neighborhoodArea?: string | null;
  coordinator?: {
    name?: string | null;
    phone?: string | null;
  };
  meetingDay?: ('sunday' | 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday') | null;
  /**
   * Full schedule description (e.g. "Every second Friday at 6pm").
   */
  meetingSchedule?: string | null;
  /**
   * Approximate number of member households.
   */
  memberCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages submitted via the public contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  subject: string;
  message: string;
  status: 'new' | 'read' | 'replied' | 'archived';
  /**
   * Timestamp when this message was submitted.
   */
  submittedAt?: string | null;
  /**
   * Internal notes (not visible to submitter).
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'parishes';
        value: number | Parish;
      } | null)
    | ({
        relationTo: 'ministries';
        value: number | Ministry;
      } | null)
    | ({
        relationTo: 'priests';
        value: number | Priest;
      } | null)
    | ({
        relationTo: 'pope-messages';
        value: number | PopeMessage;
      } | null)
    | ({
        relationTo: 'bishop-messages';
        value: number | BishopMessage;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'magazines';
        value: number | Magazine;
      } | null)
    | ({
        relationTo: 'archives';
        value: number | Archive;
      } | null)
    | ({
        relationTo: 'schools';
        value: number | School;
      } | null)
    | ({
        relationTo: 'clinics';
        value: number | Clinic;
      } | null)
    | ({
        relationTo: 'children-programs';
        value: number | ChildrenProgram;
      } | null)
    | ({
        relationTo: 'small-christian-communities';
        value: number | SmallChristianCommunity;
      } | null)
    | ({
        relationTo: 'geez-calendar-entries';
        value: number | GeezCalendarEntry;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  assignedParish?: T;
  profilePhoto?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  heroImage?: T;
  hero?:
    | T
    | {
        heading?: T;
        subheading?: T;
      };
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  category?: T;
  featuredImage?: T;
  excerpt?: T;
  body?: T;
  author?: T;
  relatedNews?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  eventType?: T;
  featuredImage?: T;
  excerpt?: T;
  description?: T;
  startDate?: T;
  endDate?: T;
  isAllDay?: T;
  location?:
    | T
    | {
        name?: T;
        address?: T;
        googleMapsUrl?: T;
      };
  parish?: T;
  organizer?: T;
  isRecurring?: T;
  geezCalendarRef?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parishes_select".
 */
export interface ParishesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  vicariate?: T;
  region?: T;
  featuredImage?: T;
  patron?: T;
  feastDate?: T;
  description?: T;
  history?: T;
  pastor?: T;
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
        mapUrl?: T;
      };
  massTimes?:
    | T
    | {
        day?: T;
        time?: T;
        language?: T;
        notes?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries_select".
 */
export interface MinistriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  type?: T;
  featuredImage?: T;
  description?: T;
  mission?: T;
  parish?: T;
  leader?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
      };
  meetingInfo?:
    | T
    | {
        schedule?: T;
        venue?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "priests_select".
 */
export interface PriestsSelect<T extends boolean = true> {
  fullName?: T;
  slug?: T;
  title?: T;
  status?: T;
  photo?: T;
  assignment?: T;
  bio?: T;
  parish?: T;
  ordinationDate?: T;
  birthDate?: T;
  education?:
    | T
    | {
        institution?: T;
        degree?: T;
        year?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pope-messages_select".
 */
export interface PopeMessagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  documentType?: T;
  featuredImage?: T;
  excerpt?: T;
  body?: T;
  document?: T;
  sourceUrl?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bishop-messages_select".
 */
export interface BishopMessagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  messageType?: T;
  featuredImage?: T;
  excerpt?: T;
  body?: T;
  document?: T;
  isFeatured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  language?: T;
  publishedAt?: T;
  coverImage?: T;
  description?: T;
  file?: T;
  fileSize?: T;
  pageCount?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazines_select".
 */
export interface MagazinesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  coverImage?: T;
  issueNumber?: T;
  year?: T;
  volume?: T;
  description?: T;
  document?: T;
  featuredArticles?:
    | T
    | {
        articleTitle?: T;
        pageNumber?: T;
        author?: T;
        id?: T;
      };
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archives_select".
 */
export interface ArchivesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  year?: T;
  category?: T;
  accessLevel?: T;
  description?: T;
  files?:
    | T
    | {
        file?: T;
        label?: T;
        language?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools_select".
 */
export interface SchoolsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  level?: T;
  featuredImage?: T;
  description?: T;
  parish?: T;
  contact?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
      };
  principalName?: T;
  foundedYear?: T;
  studentCount?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinics_select".
 */
export interface ClinicsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  facilityType?: T;
  featuredImage?: T;
  description?: T;
  parish?: T;
  contact?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
      };
  services?:
    | T
    | {
        serviceName?: T;
        description?: T;
        id?: T;
      };
  openingHours?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "children-programs_select".
 */
export interface ChildrenProgramsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  ageGroup?: T;
  featuredImage?: T;
  description?: T;
  curriculum?: T;
  parish?: T;
  coordinator?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
      };
  schedule?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "small-christian-communities_select".
 */
export interface SmallChristianCommunitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  parish?: T;
  description?: T;
  neighborhoodArea?: T;
  coordinator?:
    | T
    | {
        name?: T;
        phone?: T;
      };
  meetingDay?: T;
  meetingSchedule?: T;
  memberCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "geez-calendar-entries_select".
 */
export interface GeezCalendarEntriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isFasting?: T;
  feastRank?: T;
  liturgicalColor?: T;
  geezDate?:
    | T
    | {
        month?: T;
        day?: T;
      };
  gregorianEquivalent?:
    | T
    | {
        month?: T;
        day?: T;
      };
  saint?: T;
  description?: T;
  readings?:
    | T
    | {
        firstReading?: T;
        psalm?: T;
        gospel?: T;
      };
  fastingNotes?: T;
  relatedEvents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  submittedAt?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site identity, contact info, and metadata defaults.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Short tagline displayed in the browser tab and meta tags.
   */
  tagline?: string | null;
  /**
   * Default meta description (160 chars max).
   */
  siteDescription?: string | null;
  /**
   * Main site logo. Recommended: SVG or PNG with transparent background.
   */
  logo?: (number | null) | Media;
  /**
   * Dark variant of the logo (used on light backgrounds).
   */
  logoDark?: (number | null) | Media;
  /**
   * Favicon image (ICO or 32×32 PNG).
   */
  favicon?: (number | null) | Media;
  /**
   * Default Open Graph image (1200×630px) for social sharing.
   */
  defaultOgImage?: (number | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
    fax?: string | null;
    address?: {
      street?: string | null;
      city?: string | null;
      region?: string | null;
      country?: string | null;
      poBox?: string | null;
    };
    /**
     * Google Maps embed URL for the contact page map.
     */
    mapEmbedUrl?: string | null;
  };
  socialLinks?: {
    /**
     * Full Facebook page URL.
     */
    facebook?: string | null;
    /**
     * Full YouTube channel URL.
     */
    youtube?: string | null;
    /**
     * Full Twitter/X profile URL.
     */
    twitter?: string | null;
    /**
     * Telegram channel link.
     */
    telegram?: string | null;
    instagram?: string | null;
  };
  analytics?: {
    /**
     * GA4 Measurement ID (G-XXXXXXXXXX).
     */
    googleAnalyticsId?: string | null;
    /**
     * GTM Container ID (GTM-XXXXXXX).
     */
    googleTagManagerId?: string | null;
  };
  /**
   * Enable maintenance mode to show a holding page to visitors.
   */
  maintenanceMode?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site header: logo, announcement banner, and utility links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Logo image shown in the site header. Overrides the SiteSettings logo.
   */
  logo?: (number | null) | Media;
  /**
   * Alt text for the header logo.
   */
  logoAlt?: string | null;
  /**
   * Optional banner shown above the main navigation.
   */
  announcementBanner?: {
    enabled?: boolean | null;
    message?: string | null;
    /**
     * Optional URL the banner message links to.
     */
    link?: string | null;
    style?: ('info' | 'warning' | 'urgent') | null;
  };
  utilityLinks?:
    | {
        label: string;
        url: string;
        /**
         * Optional icon name (e.g. phone, mail).
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site footer: link columns, social icons, and copyright text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Copyright notice (e.g. "© 2025 Eparchy of Segeneyti. All rights reserved.").
   */
  copyrightText?: string | null;
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              url: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Small links in the very bottom bar (Privacy Policy, Terms, etc.).
   */
  bottomLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Display social media icons in the footer (sourced from Site Settings).
   */
  showSocialLinks?: boolean | null;
  newsletterSignup?: {
    enabled?: boolean | null;
    heading?: string | null;
    subtext?: string | null;
    placeholder?: string | null;
    buttonLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage hero, featured content, and section toggles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    /**
     * Main hero heading text.
     */
    headline?: string | null;
    subheading?: string | null;
    backgroundImage?: (number | null) | Media;
    primaryCta?: {
      label?: string | null;
      url?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      url?: string | null;
    };
  };
  bishopMessage?: {
    enabled?: boolean | null;
    /**
     * Pin a specific message, or leave blank to use the latest.
     */
    featuredMessage?: (number | null) | BishopMessage;
    sectionHeading?: string | null;
    sectionSubtext?: string | null;
  };
  latestNews?: {
    enabled?: boolean | null;
    sectionHeading?: string | null;
    /**
     * Number of news items to display.
     */
    count?: number | null;
    /**
     * Pin specific articles. Leave empty to show latest published.
     */
    featuredArticles?: (number | News)[] | null;
  };
  upcomingEvents?: {
    enabled?: boolean | null;
    sectionHeading?: string | null;
    /**
     * Number of events to display.
     */
    count?: number | null;
  };
  quickLinks?: {
    enabled?: boolean | null;
    sectionHeading?: string | null;
    links?:
      | {
          label: string;
          url: string;
          /**
           * Lucide icon name or emoji.
           */
          icon?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Main site navigation structure with optional mega-menu dropdowns.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Top-level navigation items. Each item can have a dropdown with sub-links.
   */
  mainNav?:
    | {
        label: string;
        /**
         * Leave blank if this item is a dropdown parent only.
         */
        url?: string | null;
        openInNewTab?: boolean | null;
        children?:
          | {
              label: string;
              url: string;
              /**
               * Short description shown in mega-menu dropdowns.
               */
              description?: string | null;
              /**
               * Optional Lucide icon name.
               */
              icon?: string | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Additional links shown only in the mobile navigation drawer (e.g. Live Stream, Give).
   */
  mobileExtra?:
    | {
        label: string;
        url: string;
        /**
         * Show as a highlighted button.
         */
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  siteDescription?: T;
  logo?: T;
  logoDark?: T;
  favicon?: T;
  defaultOgImage?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        fax?: T;
        address?:
          | T
          | {
              street?: T;
              city?: T;
              region?: T;
              country?: T;
              poBox?: T;
            };
        mapEmbedUrl?: T;
      };
  socialLinks?:
    | T
    | {
        facebook?: T;
        youtube?: T;
        twitter?: T;
        telegram?: T;
        instagram?: T;
      };
  analytics?:
    | T
    | {
        googleAnalyticsId?: T;
        googleTagManagerId?: T;
      };
  maintenanceMode?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  logoAlt?: T;
  announcementBanner?:
    | T
    | {
        enabled?: T;
        message?: T;
        link?: T;
        style?: T;
      };
  utilityLinks?:
    | T
    | {
        label?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  copyrightText?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  bottomLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  showSocialLinks?: T;
  newsletterSignup?:
    | T
    | {
        enabled?: T;
        heading?: T;
        subtext?: T;
        placeholder?: T;
        buttonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        subheading?: T;
        backgroundImage?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  bishopMessage?:
    | T
    | {
        enabled?: T;
        featuredMessage?: T;
        sectionHeading?: T;
        sectionSubtext?: T;
      };
  latestNews?:
    | T
    | {
        enabled?: T;
        sectionHeading?: T;
        count?: T;
        featuredArticles?: T;
      };
  upcomingEvents?:
    | T
    | {
        enabled?: T;
        sectionHeading?: T;
        count?: T;
      };
  quickLinks?:
    | T
    | {
        enabled?: T;
        sectionHeading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              icon?: T;
              description?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              description?: T;
              icon?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  mobileExtra?:
    | T
    | {
        label?: T;
        url?: T;
        highlight?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}