/**
 * payload-types.ts
 *
 * This file is AUTO-GENERATED by `npm run generate:types`.
 * Run that command after any collection/global schema changes.
 * DO NOT edit manually.
 *
 * This is a placeholder stub so TypeScript compiles before first generation.
 */

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface Config {}

export type CollectionSlug =
  | 'users'
  | 'media'
  | 'pages'
  | 'news'
  | 'events'
  | 'parishes'
  | 'ministries'
  | 'priests'
  | 'pope-messages'
  | 'bishop-messages'
  | 'publications'
  | 'magazines'
  | 'archives'
  | 'schools'
  | 'clinics'
  | 'children-programs'
  | 'small-christian-communities'
  | 'geez-calendar-entries'
  | 'contact-submissions'

export type GlobalSlug =
  | 'site-settings'
  | 'header'
  | 'footer'
  | 'homepage'
  | 'navigation'
