import type { CollectionConfig } from 'payload'

/**
 * Fixed-window rate-limit counters.
 *
 * Exists as a Payload collection purely so the table and its unique index are
 * generated by `migrate:create` like everything else — it is never read or
 * written through the Payload API. All access goes through
 * lib/security/rateLimit, which issues a single atomic `INSERT … ON CONFLICT`
 * so concurrent serverless invocations cannot lose an increment.
 *
 * Why Postgres and not an in-memory counter: on Vercel each request may hit a
 * different instance, so a process-local map counts a fraction of the traffic
 * and rate-limits nobody. Why not Redis/Upstash: Neon is already a dependency
 * with pooling configured, and this adds a few hundred writes a day — a new
 * vendor, secret, and failure mode would cost more than it buys. The store is
 * isolated behind one module, so swapping it later touches one file.
 *
 * PRIVACY: `bucket` holds an action name plus an HMAC of the client IP (see
 * lib/security/clientId). No raw IP is ever written here — this table must not
 * become the place the application starts holding PII.
 */
export const RateLimits: CollectionConfig = {
  slug: 'rate-limits',
  admin: {
    // Operational plumbing, not content: never shown in the sidebar.
    hidden: true,
    useAsTitle: 'bucket',
    group: 'Administration',
    description: 'Internal rate-limit counters. Written by the server only.',
  },
  access: {
    // No one reads or writes this through the API — not even a super-admin.
    // The limiter bypasses access control with a direct SQL statement.
    read: () => false,
    create: () => false,
    update: () => false,
    delete: () => false,
  },
  indexes: [
    // Makes the upsert's ON CONFLICT target valid, and keeps lookups cheap.
    { fields: ['bucket', 'windowStart'], unique: true },
  ],
  fields: [
    {
      name: 'bucket',
      type: 'text',
      required: true,
      index: true,
      admin: { description: 'action:hashedClient — never a raw IP address.' },
    },
    {
      name: 'windowStart',
      type: 'date',
      required: true,
      index: true,
      admin: { description: 'Start of the fixed window this counter belongs to.' },
    },
    {
      name: 'count',
      type: 'number',
      required: true,
      defaultValue: 0,
      admin: { description: 'Requests seen in this window.' },
    },
  ],
  timestamps: true,
}
