import fs from 'node:fs'
import path from 'node:path'
import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

interface SeedDay {
  geezLabel: string
  month: string
  day: number
  geezYear: number
  gregorianDate: string
  readings: string
  antiphon: string
  deceasedClergy: string
  events: string
}

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_geez_calendar_days_month" AS ENUM('meskerem', 'tikimit', 'hidar', 'tahsas', 'tir', 'yekatit', 'megabit', 'miyazia', 'ginbot', 'sene', 'hamle', 'nehase', 'paguemen');
  CREATE TABLE "geez_calendar_days" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"geez_label" varchar NOT NULL,
  	"month" "enum_geez_calendar_days_month" NOT NULL,
  	"day" numeric NOT NULL,
  	"geez_year" numeric NOT NULL,
  	"gregorian_date" timestamp(3) with time zone NOT NULL,
  	"readings" varchar,
  	"antiphon" varchar,
  	"deceased_clergy" varchar,
  	"events" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "geez_calendar_days_id" integer;
  CREATE INDEX "geez_calendar_days_month_idx" ON "geez_calendar_days" USING btree ("month");
  CREATE INDEX "geez_calendar_days_gregorian_date_idx" ON "geez_calendar_days" USING btree ("gregorian_date");
  CREATE INDEX "geez_calendar_days_updated_at_idx" ON "geez_calendar_days" USING btree ("updated_at");
  CREATE INDEX "geez_calendar_days_created_at_idx" ON "geez_calendar_days" USING btree ("created_at");
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_geez_calendar_days_fk" FOREIGN KEY ("geez_calendar_days_id") REFERENCES "public"."geez_calendar_days"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "payload_locked_documents_rels_geez_calendar_days_id_idx" ON "payload_locked_documents_rels" USING btree ("geez_calendar_days_id");`)

  // ── Import the Ge'ez year from the converted calendar data ─────────────────
  // Generated by scripts/convert-geez-calendar.mjs from the eparchy's
  // liturgical calendar JSON.
  const dataPath = path.resolve(process.cwd(), 'src/migrations/data/geez-calendar-days.json')
  if (!fs.existsSync(dataPath)) {
    payload.logger.warn(`geez calendar seed file missing at ${dataPath}; skipping import`)
    return
  }
  const rows = JSON.parse(fs.readFileSync(dataPath, 'utf8')) as SeedDay[]

  const CHUNK = 60
  for (let i = 0; i < rows.length; i += CHUNK) {
    const chunk = rows.slice(i, i + CHUNK)
    const values = sql.join(
      chunk.map(
        (r) =>
          sql`(${r.geezLabel}, ${r.month}, ${r.day}, ${r.geezYear}, ${r.gregorianDate}, ${r.readings || null}, ${r.antiphon || null}, ${r.deceasedClergy || null}, ${r.events || null})`,
      ),
      sql`, `,
    )
    await db.execute(
      sql`INSERT INTO "geez_calendar_days" ("geez_label", "month", "day", "geez_year", "gregorian_date", "readings", "antiphon", "deceased_clergy", "events") VALUES ${values}`,
    )
  }
  payload.logger.info(`Imported ${rows.length} geez calendar days`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "geez_calendar_days" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "geez_calendar_days" CASCADE;
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_geez_calendar_days_fk";
  
  DROP INDEX "payload_locked_documents_rels_geez_calendar_days_id_idx";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "geez_calendar_days_id";
  DROP TYPE "public"."enum_geez_calendar_days_month";`)
}
